global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'neverdown'
    static_configs:
      - targets: ['neverdown:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
